Models/Chef.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
// one more for custom validations - future date
// one more for custom validations - 18 y/o and up


namespace CSChefNDish.Models
{
    public class Chef
    {
        [Key]
        public int ChefId { get; set; }         //dont forget PK from MySQL DB!! and mark it [Key] for the framework


        [Required(ErrorMessage = "...required!")]
        [Display(Name = "First Name")]
        public string First { get; set; }


        [Required(ErrorMessage = "...required!")]
        [Display(Name = "Last Name")]
        public string Last { get; set; }


        [DataType(DataType.Date)] 
        [Required(ErrorMessage = "...required!")]
        // [FutureDate(ErrorMessage="...must be a past date!")]
        // [Adult(ErrorMessage="...min must be 18 y/o!")]
        [Display(Name="Date of Birth")]
        public DateTime Birthdate { get; set; }


        //[DataType(DataType.Date)]     //not displaying
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        //[DataType(DataType.Date)]     //not displaying
        public DateTime UpdatedAt { get; set; } = DateTime.Now;


        public int Age(){
            int age = DateTime.Now.Year - this.Birthdate.Year;  
            if (DateTime.Now.DayOfYear < this.Birthdate.DayOfYear)  
                {age = age - 1;}  
            return age;
        }

        //One Chef can have Many Dishes;
        //Each Dish is created by One Chef
        public List<Dish> createdDishes { get; set;}

    }
}

Controllers/ChefsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CSChefNDish.Models;
using Microsoft.EntityFrameworkCore;

//using Microsoft.AspNetCore.Http;
// HttpContext.Session.SetString("key","")/.GetString("key")/.GetInt32("key",)/.GetInt32("key")
// HttpContext.Session.Clear();
// TempData["var"] = "";  //persist across one redirect only


namespace CSChefNDish.Controllers
{
    public class ChefsController : Controller
    {
        private dbChefNDishContext db;
        public ChefsController(dbChefNDishContext dbContext)
        {
            db = dbContext;
        }

        [HttpGet("")]               //overrides the ones in Home Controller ?? 
        public IActionResult Index()
        {
            // // Retreiving just List<Chef> would work as long as 
            // // its View is also just expecting List<Chef>
            // List<Chef> chefs = db.Chefs
            //     .Include(m => m.createdDishes)
            //     .OrderByDescending(c => c.ChefId).ToList();
            // return View(chefs);

            //First + Last
            //Age = DateTime.Now - BirthDate
            //# of Dishes = db.Chefs.include(m = > m.createdDishes).createdDishes.Count;

            // Also Works!
            ChefNDish chefnDish = new ChefNDish()
            {
                NewDish = new Dish(),
                ListOfChefs = db.Chefs
                    .Include(c => c.createdDishes)
                    .OrderByDescending(c => c.ChefId).ToList()
            };
            return View(chefnDish);
        }

        [HttpGet("/Chef/New")]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost("/Chef/Create")]
        public IActionResult Create(Chef newChef)
        {
            if (ModelState.IsValid == false)
            {
                return View("New");                     //Just "New" - already in Chef
            }
            // ModalState.IsValid...
            // newDish.CreatedAt = DateTime.Now;        //works, but moved to Model's instantiation
            db.Chefs.Add(newChef);                      //DB Insert
            db.SaveChanges();
            return RedirectToAction("Index");
            // return RedirectToAction("Details", newDish.DishId);  //"Details", new {id = newDish.DishId}
        }

        public IActionResult Privacy()
        {
            return View();
        }


    }
}

Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CSChefNDish.Models;
using Microsoft.AspNetCore.Mvc;
// using CSChefNDish.Models;
using Microsoft.EntityFrameworkCore;

//using Microsoft.AspNetCore.Http;
// HttpContext.Session.SetString("key","")/.GetString("key")/.GetInt32("key",)/.GetInt32("key")
// HttpContext.Session.Clear();
// TempData["var"] = "";  //persist across one redirect only


namespace CSChefNDish.Controllers
{
    public class DishesController : Controller
    {
        private dbChefNDishContext db;
        public DishesController(dbChefNDishContext dbContext)
        {
            db = dbContext;
        }

        [HttpGet("/Dishes")]                         //overrides the ones in Home Controller ?? 
        public IActionResult All()
        {
            // List<Dish> dishes = db.Dishes.Reverse().ToList();
            List<Dish> dishes = db.Dishes
                .Include(d => d.dishChef)
                .OrderByDescending(d => d.CreatedAt).ToList();
            return View(dishes);
        }

        [HttpGet("/Dish/New")]  
        public IActionResult New()
        {
            ChefNDish chefnDish = new ChefNDish()
            {
                NewDish = new Dish(),
                ListOfChefs = db.Chefs.ToList()
            };

            return View(chefnDish);
        }

        [HttpPost("/Dish/Create")]  
        public IActionResult Create(ChefNDish newChefNDish)                                     //Dish newDish    //param retrieval MUST match @model passback!
        
        {
            if (ModelState.IsValid == false)
            {
                // return View("New");                                                          //not enough, the Dish/New view also needs ListOfChefs
                newChefNDish.ListOfChefs = db.Chefs.ToList();
                return View("New",newChefNDish);
            }
            // ModalState.IsValid...
            //db.Dishes.Add(newChefNDish.NewDish);                                          //DB Insert
            db.Dishes.Add(newChefNDish.NewDish);
            db.SaveChanges();
            return RedirectToAction("All");                                         //"Details", new {id = newDish.DishId}
        }























    //     //defaultMVCRoute: /Dish/Details/4
    //     //exploring "id" as route param
    //     public IActionResult Details(int id)
    //     {
    //         Dish selectedDish = db.Dishes.FirstOrDefault(d => d.DishId == id);
    //         if (selectedDish == null)
    //         {
    //             return RedirectToAction("Index");
    //         }
    //         return View(selectedDish);
    //     }

    //     //defaultMVCRoute: /Dish/Edit/1
    //     //HttpRoute takes precedence: /Home/1/Edit
    //     //exploring "id" as route param
    //     //exploring HttpRoute - apply this route when avail, without this use default MVCRoute
    //     [HttpGet("/Dish/{id}/Edit")]
    //     public IActionResult Edit(int id)
    //     {
    //         Dish selectedDish = db.Dishes.FirstOrDefault(d => d.DishId == id);
    //         if (selectedDish == null)
    //         {
    //             return RedirectToAction("Index");
    //         }
    //         return View(selectedDish);
    //     }


    //     // RESTful route: /Dish/1/Update
    //     // exploring "id" as route param
    //     // [HttpPost("/Dish/{dishId}/Update")]     //dishId  //id = "This page isn't working"
    //     public IActionResult Update(Dish updatedDish, int dishId)       
    //     {
    //         if (ModelState.IsValid == false)
    //         {
    //             return View("Edit", updatedDish);  //correct way - get the new updated model with errors displayed
    //          // return RedirectToAction("Edit", dishId);        //??? why wouldnt this work - breakpoint shows updatedDish.DishId has a valid id
    //          //??? want to learn this error troubleshoot - I know logically the View version makes more sense 
    //         }

    //         // updatedDish.DishId only works if asp-route- on <form> use asp-route-dishId, 
    //         // frmwk knows to match it using asp-route-dishId withOUT the (... , int dishId) input param
    //         //Dish dbDish = db.Dishes.FirstOrDefault(d => d.DishId == updatedDish.DishId);    
    //         Dish dbDish = db.Dishes.FirstOrDefault(d => d.DishId == dishId);
    //         if (dbDish == null)
    //         {
    //             return RedirectToAction("Index");
    //         }
    //         dbDish.Name = updatedDish.Name;
    //         dbDish.Chef = updatedDish.Chef;
    //         dbDish.Description = updatedDish.Description;
    //         dbDish.Calories = updatedDish.Calories;
    //         dbDish.Tastiness = updatedDish.Tastiness;
    //         dbDish.UpdatedAt = DateTime.Now;
            
    //         db.Dishes.Update(dbDish);           // NOT Update(updatedDish) - it would override CreatedAt timestamp as well.
    //         db.SaveChanges();
    //         return RedirectToAction("Details",new{id = dbDish.DishId});     //RedirectToAction MUST HAVE object route param format in dict format if included, hence new{ x = xxx}   
    //         // return RedirectToAction("/Home/Details/{dishId}", dishId);   //- Err: No route matches the supplied values
    //         // return View("Details",dbDish);               //works
    //         // return RedirectToAction("Index");            //works, not good enough
    //         // return View("test", updatedDish.DishId);     //works
    //     }

    // //defaultMVCRoute: /Dish/Delete/4  
    //     //exploring "id" as route param
    //     public IActionResult Delete(int id)
    //     {
    //         // not checking null here - not needed - Default would be null if not found, will send to Index anyway
    //         db.Dishes.Remove(db.Dishes.FirstOrDefault(d => d.DishId == id));
    //         db.SaveChanges();
    //         return RedirectToAction("Index");
    //     }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Chefs/Index.cshtml
@{
    ViewData["Title"] = "Chef - All Chefs";
}

@* @model List<Chef>   //Works when List<Chef> in Index()! *@
@model ChefNDish       //Also Works! 

<div>
    <div class="text-center">
        <h3 class="">Chefs | 
        <a asp-controller="Dishes" asp-action="All"> Dishes</a></h3>
    </div>
    <div class="d-flex justify-content-between ">
        <p class="">Check out our roster of Chefs!</p>
        <div>
            <a asp-action="New" asp-controller="Chefs" >Add a Chef</a>
            @* <a asp-action="New" asp-controller="Dishes" >Add a Dish</a> *@
            @* <a href="/Chefs/New">Add a Chef</a> *@
        </div>
    </div>
    <hr>

<table class="table table-striped table-dark">
    <thead class="thead-light">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Bdate</th>
        <th scope="col">Age</th>
        <th scope="col"># of Dishes</th>
        </tr>
    </thead>
    <tbody>
    @* @foreach (Chef c in Model) *@
    @foreach (Chef c in Model.ListOfChefs)
    {
        @* int age = DateTime.Now.Year - c.Birthdate.Year;  
        if (DateTime.Now.DayOfYear < c.Birthdate.DayOfYear)  
            {age = age - 1;}   *@
    
        <tr>
        <th scope="row">@c.ChefId</th>
        <td>@c.First @c.Last</td>
        <td>@c.Birthdate.ToShortDateString()</td>
        @* <td>@c.Birthdate.ToLongDateString()</td> *@
        @* <td>@(DateTime.Now.Year-c.Birthdate.Year)</td>   *@
        @* <td>@age</td> *@  @* if using above razor age calc code *@
        <td>@c.Age()</td>
        <td>@c.createdDishes.Count</td>
        </tr>
    }
    </tbody>
</table>

</div>


@* 
    @foreach (Chef c in Model)
    {
        <p><a asp-route-id="@d.DishId" asp-action="Details" asp-controller="Dish">@d.Name</a><br> 
            <small>by @d.Chef</small><br>
            <small>created at @d.CreatedAt</small><br> 
            <small>updated at @d.UpdatedAt</small> 
        </p>
    } 
*@

Views/Chefs/New.cshtml
@{
ViewData["Title"] = "Chef - Add New";
}


@model Chef

<div>
    <div class="text-center">
        <h3 class="">Add a Chef!</h3>
    </div>
    <div class="d-flex justify-content-left">
        <a a asp-action="Index" asp-controller="Chefs">Back to Chefs List</a>
    </div>
    <hr>

    <form asp-action="Create" asp-controller="Chefs" method="post">
        <div class="row">
            <div class="form-group col-sm ">
                <label asp-for="First"></label>
                <span asp-validation-for="First" class="salmon"></span>
                <input asp-for="First" class="form-control mb-3">

                <label asp-for="Last"></label>
                <span asp-validation-for="Last" class="salmon"></span>
                <input asp-for="Last" class="form-control mb-3">
            </div>

            <div class="form-group col-sm ">
                <label asp-for="Birthdate"></label>
                <span asp-validation-for="Birthdate" class="salmon"></span>
                <input asp-for="Birthdate" class="form-control mb-3">

                <button type="submit" class="btn btn-outline-warning mt-3">Add Chef</button>
                @* <input type="submit" value="Add Dish"> *@
            </div>

        </div>
    </form>
</div>

@* Template: ASP.Net Core form with Validation
<form asp-action="Create" asp-controller="Chefs" method="POST">
    <div class="form-group">
        <label asp-for=""></label>
        <span asp-validation-for="" class="text-danger"></span>
        <input asp-for="" class="form-control">
    </div>

</form> *@